<template>
  <div id="app">
    <h1>{{ headerText }}</h1>
    <p v-if="gameIsFinished === false" class="gameStatusHolder">
      <span v-if="currentTurn === 'White'">&#9898;</span>
      <span v-else>&#9899;</span>
      {{ currentTurn }}'s turn
    </p>
    <p v-else class="gameStatusHolder">
      <span>Game Finished!</span>
      <span v-html="checkWhoWon()"></span>
      <button v-on:click="() => startGame()">New Game</button>
    </p>
    <div class="boardHolder">
      <div class="board" v-bind:style="{ cursor: hoverImage }">
        <div v-for="(row, rowIndex) in boardArray" :key="rowIndex">
          <div class="row">
            <div v-for="(square, squareIndex) in row" :key="squareIndex">
              <div v-if="square.animated === true">
                <Square
                  :piece="square.piece"
                  :row="square.row"
                  :column="square.column"
                  :isAnimated="square.animated"
                  :animationDelay="square.animationDelay"
                />
              </div>
              <div v-else>
                <Square :piece="square.piece" :row="square.row" :column="square.column" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="scoreHolder">
      <div>&#9898; White Pieces: {{ numOfWhitePieces }}</div>
      <div>&#9899; Black Pieces: {{ numOfBlackPieces }}</div>
    </div>
  </div>
</template>




<script>
//component imports
import Square from "./components/Square.vue";
//import func from '../vue-temp/vue-editor-bridge'; I don't know where this line of code came from, it wasn't in the autogenerated empty project and I didn't put it here
import whiteCircle from "./assets/white-circle.png";
import blackCircle from "./assets/black-circle.png";
import { Sound } from "./sound.js";

export default {
  name: "app",
  components: {
    Square
  },

  methods: {
    /**
     * Sets a piece on the board based on whose turn it is. Will flip any pieces that need to be flipped
     */
    setPiece: function(event, piece, row, column) {
      //first, we have to check if a piece can be set here. A piece can't be set if a piece is already here, or if placing a piece here wouldn't do flip anything

      console.log("===========================");
      console.log("a piece is attempting to be set");
      console.log(
        "It is currently " + piece + ` at coordinates = (${column},${row})`
      );
      if (piece === null && this.gameIsFinished === false) {
        this.boardArray[row][column].piece =
          this.currentTurn === "White" ? "white" : "black";
        //console.log(this.boardArray[row][column]);
        this.currentTurn = this.currentTurn === "White" ? "Black" : "White";
        this.hoverImage =
          this.currentTurn === "White"
            ? this.hoverImageWhite
            : this.hoverImageBlack;

        console.log("new piece value is " + this.boardArray[row][column].piece);

        //now that a piece is set, we have to check for surrounding pieces. There are 8 possible directions to check for.
        //remember the pieces in the array are organized into this.boardArray[row][column]
        let piecesToBeFlipped = [];
        let allPieces = [];

        //FIXME: Line 46 switches the turns early. Once that is moved, swap the two white and black conditionals around
        let opponentPieceColor =
          this.currentTurn === "White" ? "white" : "black"; //if our piece is white, opponent piece is black and vice versa
        let myColor = this.currentTurn === "White" ? "black" : "white";

        //checking UP
        for (let i = row - 1; i >= 0; i--) {
          console.log(
            "checking above row = " + (i + 1) + " column = " + column
          );
          if (this.boardArray[i][column].piece === opponentPieceColor) {
            //if the piece above is not my color
            console.log(
              "piece above was " +
                opponentPieceColor +
                ` at (${this.boardArray[i][column].column},${this.boardArray[i][column].row}). Adding it to the pieces to be flipped`
            );
            piecesToBeFlipped.push({ row: i, column: column }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[i][column].piece === myColor) {
            //if the piece above is equal to my color,
            console.log(
              `piece above is ${myColor} at row ${i} column ${column}. flipping array`
            );
            console.log(`Flipping ${piecesToBeFlipped.length} pieces...`);
            console.log(piecesToBeFlipped);

            //add the current array to the larger array of all pieces that need to be flipped
            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[i][column].piece === null) {
            console.log(
              "piece above was null at row = " + i + ", column = " + column
            );
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //EACH CHECK IS BASED ON THE FIRST, SO CONSOLE LOGS ARE REMOVED FOR THE SAKE OF READABILITY

        //checking DOWN
        for (let i = row + 1; i <= 7; i++) {
          console.log("checking down");
          if (this.boardArray[i][column].piece === opponentPieceColor) {
            //if the piece below is not my color
            piecesToBeFlipped.push({ row: i, column: column }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[i][column].piece === myColor) {
            //if the piece below is equal to my color,

            allPieces = allPieces.concat(piecesToBeFlipped);
            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[i][column].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking LEFT
        for (let i = column - 1; i >= 0; i--) {
          console.log("checking left");
          if (this.boardArray[row][i].piece === opponentPieceColor) {
            //if the piece to the left is not my color
            piecesToBeFlipped.push({ row: row, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[row][i].piece === myColor) {
            //if the piece to the left is equal to my color,
            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[row][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking RIGHT
        for (let i = column + 1; i <= 7; i++) {
          console.log("checking right");
          if (this.boardArray[row][i].piece === opponentPieceColor) {
            //if the piece to the right is not my color
            piecesToBeFlipped.push({ row: row, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[row][i].piece === myColor) {
            //if the piece to the right is equal to my color, add the current array to my larger array

            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[row][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking TOP LEFT DIAGONAL
        for (let i = column - 1, j = row - 1; i >= 0 && j >= 0; i--, j--) {
          console.log(
            "checking top left diagonal, checking column = " +
              i +
              ", row = " +
              j
          );

          if (this.boardArray[j][i].piece === opponentPieceColor) {
            //if the piece to the right is not my color
            piecesToBeFlipped.push({ row: j, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[j][i].piece === myColor) {
            //if the piece to the right is equal to my color, add the current array to my larger array

            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[j][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking TOP RIGHT DIAGONAL
        for (let i = column + 1, j = row - 1; i <= 7 && j >= 0; i++, j--) {
          console.log("checking top right");
          //console.log("piece to the top right is row = " + j + ", column = " + i);
          if (this.boardArray[j][i].piece === opponentPieceColor) {
            //if the piece to the right is not my color
            piecesToBeFlipped.push({ row: j, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[j][i].piece === myColor) {
            //if the piece to the right is equal to my color, add the current array to my larger array

            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[j][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking BOTTOM RIGHT DIAGONAL
        for (let i = column + 1, j = row + 1; i <= 7 && j <= 7; i++, j++) {
          console.log("checking bottom right");
          //console.log("piece to the top right is row = " + j + ", column = " + i);
          if (this.boardArray[j][i].piece === opponentPieceColor) {
            //if the piece to the right is not my color
            piecesToBeFlipped.push({ row: j, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[j][i].piece === myColor) {
            //if the piece to the right is equal to my color, add the current array to my larger array

            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[j][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //checking BOTTOM LEFT DIAGONAL
        for (let i = column - 1, j = row + 1; i >= 0 && j <= 7; i--, j++) {
          console.log("checking bottom left");
          //console.log("piece to the top right is row = " + j + ", column = " + i);
          if (this.boardArray[j][i].piece === opponentPieceColor) {
            //if the piece to the right is not my color
            piecesToBeFlipped.push({ row: j, column: i }); //get it ready to be flipped, add it to the array
          } else if (this.boardArray[j][i].piece === myColor) {
            //if the piece to the right is equal to my color, add the current array to my larger array

            allPieces = allPieces.concat(piecesToBeFlipped);

            break; //break, you already flipped everything here you need to
          } else if (this.boardArray[j][i].piece === null) {
            break; //if you reached a null piece without first reaching your own piece, break and don't flip
          }
        }
        piecesToBeFlipped = [];

        //set the current piece being placed to be animated
        this.boardArray[row][column].animated = true;
        this.boardArray[row][column].animationDelay = 0; //this piece will be dropped with no delay

        //set the animation timer to its default
        this.animationTimer = 250;
        //play the sound and delay it so it syncs up with the animation
        setTimeout(() => this.sound.play(), 100);

        //Now that we'eve collected all the pieces that need to be flipped, flip my array
        allPieces.forEach((element, iteration) => {
          //flip all the pieces in the array that are not my color ie. the ones in between two pieces of my color
          this.boardArray[element.row][element.column].piece = myColor;
          //set the pieces that need to be animated
          this.boardArray[element.row][element.column].animated = true;
          this.boardArray[element.row][element.column].animationDelay =
            iteration + 1; //each piece will be dropped sequencially based on the iteration of this loop
          console.log("setting this pieces delay to " + (iteration + 1));

          this.animationTimer += 101; //add 101ms for each piece that needs to be flipped
        });
      } else console.log("There is already a piece on this square");

      //check the game status, see how many pieces of each color exist, and how many null pieces exist. (if there are no null squares, the game is over!)
      this.checkGameStatus();
    } /************************************************************************************************************************************END OF SET PIECE */,

    /**
     * Checks the status of the game every turn to see if its finished
     */
    checkGameStatus: function() {
      let nullPieceCount = 0;
      let whitePieceCount = 0;
      let blackPieceCount = 0;
      this.boardArray.forEach(row => {
        row.forEach(square => {
          square.piece === "white" ? whitePieceCount++ : whitePieceCount;
          square.piece === "black" ? blackPieceCount++ : blackPieceCount;
          square.piece === null ? nullPieceCount++ : nullPieceCount;
          //turn off the animation after its finished animating
          setTimeout(() => (square.animated = false), this.animationTimer);
        });
      });

      this.numOfWhitePieces = whitePieceCount;
      this.numOfBlackPieces = blackPieceCount;
      this.numOfNullSquares = nullPieceCount;

      if (this.numOfNullSquares === 0) {
        console.log("The game has completed");
        this.gameIsFinished = true;
        this.hoverImage = this.hoverImageNone;
      }
    },

    /**Puts the game in its start state */
    startGame: function() {
      console.log("Generating board...");
      this.boardArray = [];
      //generate board array
      for (let i = 0; i <= 7; i++) {
        let rowArray = [];
        for (let j = 0; j <= 7; j++) {
          rowArray.push({
            id: 1,
            row: i,
            column: j,
            piece: null,
            animated: false, //whether or not the piece will have an animation of it being dropped
            animationDelay: 0, //the delay of the animation (will be the iteration of the for loop)
            animationTimer: 250 //the time allowed for the animation to play (250ms by default because two pieces flipping is 200ms)
          });
        }
        //console.log(rowArray);
        this.boardArray.push(rowArray);
      }

      //Now, set the starting pieces
      this.boardArray[3][3].piece = "white";
      this.boardArray[4][3].piece = "black";
      this.boardArray[3][4].piece = "black";
      this.boardArray[4][4].piece = "white";

      //reset starting variables
      this.currentTurn = Math.random() > 0.5 ? "Black" : "White";
      //now set the correct hover image
      console.log("starting piece is " + this.currentTurn);
      this.hoverImage =
        this.currentTurn === "White"
          ? this.hoverImageWhite
          : this.hoverImageBlack;

      this.numOfNullSquares = this.startingEmptySquares;
      this.numOfBlackPieces, (this.numOfWhitePieces = this.startingPieces);
      this.gameIsFinished = false;
    },

    checkWhoWon: function() {
      if (this.numOfWhitePieces > this.numOfBlackPieces) {
        return "<div>&#9898; White Wins!</div>";
      } else if (this.numOfWhitePieces < this.numOfBlackPieces) {
        return "<div>&#9899; Black Wins!</div>";
      } else {
        //its a tie
        return "<div>&#9898; Tie Game! &#9899;</div>";
      }
    }
  },

  data() {
    return {
      headerText: "Othello",
      currentTurn: Math.random() > 0.5 ? "Black" : "White",
      boardArray: [],
      numOfWhitePieces: 2,
      numOfBlackPieces: 2,
      numOfNullSquares: 60,
      gameIsFinished: false,

      hoverImageWhite: "url(" + whiteCircle + ") 17.5 17.5, pointer",
      hoverImageBlack: "url(" + blackCircle + ") 17.5 17.5, pointer",
      hoverImageNone: "auto",

      //dictates which hover cursor is being used
      hoverImage: "",

      startingPieces: 2,
      startingEmptySquares: 60,

      //Chess piece sound is a free stock sound effect from https://freesound.org/people/mh2o/sounds/351518/
      sound: new Sound("../chess.wav")
    };
  },

  //run when board is created
  created: function() {
    this.startGame();
  }
};
</script>

<style>
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  display: flex;
  align-items: center;
  flex-direction: column;
  color: #2c3e50;
  margin-top: 2em;
}

h1,
h2 {
  font-weight: normal;
  margin-bottom: 0.4em;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: inline-block;
  margin: 0 10px;
}

a {
  color: #42b983;
}

.gameStatusHolder {
  font-size: 1.4em;
  margin-top: 0.2em;
}

.boardHolder {
  display: flex;
  align-items: center;
  flex-direction: column;
}

.board {
  border: 1em solid black;
}

.row {
  display: flex;
  flex-direction: row;
}

.scoreHolder {
  font-size: 1.5em;
  margin-top: 1em;
  width: 25%;
  display: flex;
  align-items: center;
  flex-direction: row;
  justify-content: space-between;
}
</style>
